#!/usr/bin/env bash
# Redirecting to another page

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo chmod 666 /var/www/html/index.nginx-debian.html
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '24i\ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx start
