#!/usr/bin/env bash
# Script creating a file
sudo touch /var/run/holbertonscript.pid
echo $$ > /var/run/holbertonscript.pid
while true
do
	trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit' SIGTERM
	trap 'rm /var/run/holbertonscript.pid; exit' SIGQUIT
	trap 'echo "Y U no love me?!"' SIGINT
	echo "To infinity and beyond"
	sleep 2
done
