#!/usr/bin/env bash
#FizzBuzz when the number is a multiple of 3(Fizz) and 5(Buzz)
for ((a=1;a<=100;a++))
do
    if ((a % 15 == 0))
    then
        echo "FizzBuzz"
    elif ((a % 3 == 0))
    then
        echo "Fizz"
    elif ((a % 5 == 0))
    then
        echo "Buzz"
    else
        echo "$a"
    fi
done
