#!/usr/bin/env bash
#Print "Best School" 10 times, but for the 9th iteration, displays Best School and then Hi
n=0
while ((a < 10))
do
    echo "Best School"
    if (($a == 8))
    then
        echo "Hi"
    fi
    a=$((a+1))
done
