#!/usr/bin/env bash
#Prints numbers from 1 to 20
a=0
while [ $a != 20 ]; do
	a=$((a + 1))
	echo $a
	case $a in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
done
