#!/usr/bin/env bash
#displays hours from 0 to 12, displays minutes from 1 to 59
minute=1
hour=0
while [ $hour != 13 ]; do
	echo "Hour: $hour"
	while [ $minute != 60 ]; do
		echo $minute
		minute=$((minute + 1))
	done
	minute=1
	hour=$((hour + 1))
done
